@isTest
private class TestUserFunctions {
    /*
    //test method for weekly attendance page
    static testMethod void testUserLoginHandleBatch(){
        Batch_UserLoginUpdate big = new Batch_UserLoginUpdate();
        
        try{
        	Database.executeBatch(big, 200);
    
        }catch(Exception e){
            //do nothing
        }
        
            
        
    }
    static testMethod void testUserLoginHandleBatch2(){
        try{
        	
            ScheduleUserLoginHandle.setup();
        }catch(Exception e){
            //do nothing
        }
    }*/
}